eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
  prefer-ip-address: true #跨域
spring:
  application:
    name: clent1
server:
  port: 9001
env ：
  dev
