spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a974389757/config.git
          username: 974389757@qq.com
          password: 900327tq
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
env:
  dev
